### ISSUE TITLE
Rename Platform to DeviceType

### ISSUE THREAD

**Issue by clairernovotny** [dotMorten/WindowsStateTriggers#1]
I can submit a PR on this in a bit if you'd like

**Comment by dotMorten** [comment]
@onovotny Sounds good!

**Comment by clairernovotny** [comment]
And by that do you mean I should submit a PR or you'll fix it directly? :P

**Comment by dotMorten** [comment]
PR 😁

**Comment by clairernovotny** [comment]
Submitted PR #7

**Comment by dotMorten** [comment]
Merged!
