### ISSUE TITLE
NuGet packages?

### ISSUE THREAD

**Issue by DaveVoyles** [dotMorten/WindowsStateTriggers#14]
When I try to run the project, I get:

Severity    Code    Description Project File    Line
Error       This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.14-beta\build\portable-net45+win8+wpa81\Microsoft.Diagnostics.Tracing.EventSource.Redist.targets.    TestApp C:\Users\davev_000\Desktop\WindowsStateTriggers-master\src\TestApp\TestApp.csproj   209

Any suggestions?

**Comment by dotMorten** [comment]
Are you using the latest Visual Studio and Windows release?
Did you attempt to run a nuget restore?

**Comment by DaveVoyles** [comment]
At that time, yes, I was.

I wasn't sure if I was missing a step in the process there, perhps a file.
I should just be able to open the solution, build it and go, correct?

Dave Voyles | DaveVoyles.com | @DaveVoyles
http://www.twitter.com/DaveVoyles

**Comment by dotMorten** [comment]
Yes - unless you disabled nuget package restore.
