### ISSUE TITLE
Add all device families to DeviceFamilyAdaptiveTrigger

### ISSUE THREAD

**Issue by robertos** [dotMorten/WindowsStateTriggers#18]
The DeviceFamilyAdaptiveTrigger supports the Phone, Desktop and universal families but not 
- [x] Team (Surface Hub). Family name: `Windows.Team`
- [x] Xbox. Family name: `Windows.Xbox`
- [x] IoT (currently returns 'Universal' but that's a bug in current release)
- [x] HoloLens. Family name: Unknown. Microsoft: Please send @dotMorten a device to test on :)

**Comment by dotMorten** [comment]
@robertos Updated issue to contain all device types. Unfortunately don't have these devices or APIs to test on. Feel free to send me a Surface Hub so I can test it ;-)

**Comment by robertos** [comment]
Now that the description says "all families", the issue is not fixed. Leave it open?

**Comment by robertos** [comment]
Xbox family is Windows.Xbox, as per published sample: https://github.com/Microsoft/Windows-universal-samples/blob/master/xaml_statetriggers/CS/MainPage.xaml#L141

**Comment by dotMorten** [comment]
Yup leave it open. Github has a weird way of auto closing issues when there are certain words in the PR being merged.

**Comment by dotMorten** [comment]
HoloLens (Holographic) added: 
https://github.com/dotMorten/WindowsStateTriggers/commit/3a97a7a45b9c997e4f59e4afd98dc1ee7e0d8a49
