### ISSUE TITLE
CompositeTrigger with OR operator is redundant

### ISSUE THREAD

**Issue by robertos** [dotMorten/WindowsStateTriggers#20]
If multiple triggers are present in the StateTriggers collection, they are treated as OR.

Source: According to published sample: https://github.com/Microsoft/Windows-universal-samples/blob/master/xaml_statetriggers/CS/MainPage.xaml#L122-125

You might decide to leave it there for a more explicit usage, but the Or operator is not necessary.

**Comment by dotMorten** [comment]
I added it mostly for completeness. But perhaps with where #21 is moving, this doesn't need to be there for completeness.

**Comment by lukeja** [comment]
If I add two triggers into StateTriggers then it ignores the second one so there is definitely a need for the OR. However the CompositeTrigger doesn't work, if I add two triggers in there then the second of the two trigger's dependency properties fail to receive any value changed notifications, if I use either of the two triggers on their own they work fine.

**Comment by dotMorten** [comment]
@lukeja I'm not sure why you need the "OR" ? If the first trigger is true, there's no need to look at the second one and can be ignored.
Wrt to the problem you're having, could you please log a bug and provide a repro in it?

**Comment by lukeja** [comment]
But if the first one is false then the second one is still ignored. I've added a bug for the issue I mentioned.

**Comment by dotMorten** [comment]
Closing this. While redundant it simplifies the API
