### ISSUE TITLE
CompositeTrigger logic for XOR operator is nor correct for more than 2 inputs

### ISSUE THREAD

**Issue by robertos** [dotMorten/WindowsStateTriggers#21]
The XOR operation is defined as true if an odd number of inputs is true, and false otherwise (source: [MathWorld](http://mathworld.wolfram.com/XOR.html)). The XOR operation defined on the [CompositeStateTrigger](https://github.com/dotMorten/WindowsStateTriggers/blob/master/src/WindowsStateTriggers/CompositeStateTrigger.cs#L53) does not respect this definition for 3 or more inputs (for example, by the mathematical definition `XOR(True,True,True) == True`, while the currently defined operation returns `False`).

We should fix or remove the current XOR operator, and possibly define a new operation which could be called "OnlyOne" that does what the current XOR does. 

(Side note: Other potentially useful operations could be "None", "NotAll", specify a maximum/minimum number of satisfied triggers, etc...)

**Comment by dotMorten** [comment]
@robertos What about a TrueCount, MinTrueCount and MaxTrueCount? (with a 'Count' property added) (ie ensure user checked two checkboxes, but not more)

**Comment by robertos** [comment]
I believe for simplicity of use we should keep the CompositeStateTrigger limited to logic operations applied to all items. Right now there's And, Or (not necessary - #20) and Only One (called Xor); I propose we make one trigger for the And, and one for Count.

Possible names:
- WhenAllStateTrigger or MultiStateTrigger - the current "And" - this was the MultiTrigger from WPF
- CompositeStateTrigger - With a MinTrueCount (int, default 0), MaxTrueCount (nullable int, if not set, consider All, or use a custom type that allows int or All)

**Comment by dotMorten** [comment]
How about renaming them to "All", "One", "Any" ?

**Comment by robertos** [comment]
That works but doesn't solve the "two checkboxes" problem. I like the idea of solving the "please select between 1 and 3 answers". We can defer that to another trigger as well.

**Comment by dotMorten** [comment]
We could get rid of it completely and set a "MinCount and MaxCount". So if you have 3 triggers, you would set them both to 3. A little less obvious though.
