### ISSUE TITLE
Add Regex state trigger

### ISSUE THREAD

**Issue by dotMorten** [dotMorten/WindowsStateTriggers#26]
Add support for a trigger that evaluates a string against a regular expression

![regextrigger](https://cloud.githubusercontent.com/assets/1378165/8049580/d72c561e-0e15-11e5-9ea4-4cb861966be9.gif)

``` xml
<triggers:RegexStateTrigger Value="{x:Bind emailTextBox.Text, Mode=OneWay}"
        Expression="^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$"
        Options="IgnoreCase"
        />
```

**Comment by robertos** [comment]
(y)

**Comment by robertos** [comment]
By which I mean "thumbs up", in Skype-speak...
