### ISSUE TITLE
Add NuSpec

### ISSUE THREAD

**Issue by clairernovotny** [dotMorten/WindowsStateTriggers#5]

**Comment by dotMorten** [comment]
Do you have any information on what the nuspec for UAP is?

**Comment by clairernovotny** [comment]
Not yet, but win81 should work until we know better.

**Comment by ScottIsAFool** [comment]
The only problem marking it as win81 is there will be someone out there that tries to use it in an actual Win81 app :)

**Comment by dotMorten** [comment]
Completed
